### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "b58aa768e785489e9035d0b76a414d58",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET  http://localhost:8080/transaction/c4d9f054a1564c82a13e14dd8507b620
